### PR TITLE
Cover broken images with their alt text

### LINKED ISSUE #30: use text for integration name when no logo is provided
On the "integrations" tab of a field, a broken image icon is shown when an integration doesn't have a logo. Pipeline Success is an example (see image below). Instead, it should show the text name.

On the integrations list, it does show text, although the name could be improved by removing "LeadConduit" from the beginning and "Integration" from the end (i.e., just "Pipeline Success").

screen shot 2016-06-22 at 2 14 33 pm

### PR DESCRIPTION
**Pull request by justinwinslow**
Fixes #30 

screen shot 2016-11-17 at 2 12 14 pm

### CODE REVIEW

**Comment by justinwinslow** [comment]
Tested in Chrome and FF. Safari is just broken so this doesn't make the situation better or worse.

**Comment by justinwinslow** [comment]
Also, FWIW, I have no idea why this works. Maybe only when images are broken are the before/after pseudo elements available?

**Comment by alexkwolfe** [comment]
Seems fine to me.

**Comment by kellym** [comment]
I like it. :+1:

**Pull request merged**
